POST http://localhost:8080/events
content-type: application/json
Authorization: replace-me

{
    "name": "some name",
    "description": "some description",
    "location": "some location",
    "date": "1990-01-01T00:00:00Z"
}